#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jan 09 23:55:43 PST 2024
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim cdb_tb_behav -key {Behavioral:sim_1:Functional:cdb_tb} -tclbatch cdb_tb.tcl -view /home/alec/hello-risc/cpu_tb_behav.wcfg -view /home/alec/hello-risc/fifo_test.wcfg -log simulate.log"
xsim cdb_tb_behav -key {Behavioral:sim_1:Functional:cdb_tb} -tclbatch cdb_tb.tcl -view /home/alec/hello-risc/cpu_tb_behav.wcfg -view /home/alec/hello-risc/fifo_test.wcfg -log simulate.log

